# Generated by Django 3.2.9 on 2021-11-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infant_id', models.TextField(default='', editable=False, max_length=100)),
                ('file', models.FileField(upload_to='txt_files/')),
            ],
        ),
    ]
