# Generated by Django 3.2.9 on 2021-11-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_csv_converter'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_information',
            name='infant_id',
            field=models.TextField(default='', editable=False, max_length=100),
        ),
    ]
