# Generated by Django 3.2.9 on 2021-11-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211106_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_information',
            old_name='address_1',
            new_name='house_add',
        ),
    ]
